---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: trailing-whitespace
            exclude: README\.md$
          - id: mixed-line-ending
            args: ['--fix=auto']
          - id: check-merge-conflict
          - id: check-vcs-permalinks
          - id: check-case-conflict
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: check-xml
            files: .*\.(xml|config)$
            types: ['file', 'text']
          - id: check-executables-have-shebangs
            files: .*\.(sh|rb)$
            types: ['file', 'text']
          - id: check-yaml
            files: .*\.(yaml|yml)$
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.1.6
      hooks:
          - id: forbid-tabs
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.11.0
      hooks:
          - id: gitlint
            name: GIT Linter
            description: Linter for Git commit message
            language: python
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.15.0
      hooks:
          - id: yamllint
            name: YAML Linter
            description: Linter for YAML files
            language: python
            args: ['-s', '-c', '.yamllint']
            files: \.(yaml|yml)$
    - repo: local
      hooks:
          - id: vagrantlint
            name: Vagrant file validation
            entry: vagrant validate Vagrantfile
            language: system
            stages: ['manual']
