# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #Box settings -- Ubuntu 14.0.5 LTS
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "theogeo"
  config.vm.define  "devpy"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = true

  # Network settings
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # Folder settings
  
  config.vm.synced_folder "../../../../../Libraries", "/scripts",
    owner: "vagrant",
    group: "vagrant",
    mount_options: ["dmode=554,fmode=554"]

  #Provider settings
  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.name = "pydev_env"
    vb.cpus = 1
    vb.memory = "1024"
  end
 
  # File provisioners
  config.vm.provision "vimrc", type: "file", source: "~/.vimrc", destination: "~/"

  # Shell provisioners

  #Vagrant user env variables
  $envvars = <<-SCRIPT
  tee "$HOME/.bashrc" <<EOF
export PS1="\\[\\033[1;36m\\]\\u\\[\\033[1;31m\\]@\\[\\033[1;32m\\]\\h:\\[\\033[1;35m\\]\\w\\[\\033[1;31m\\]\\$\\[\\033[0m\\] "
export PATH="$HOME/.local/bin:$PATH"
export PYTHONDONTWRITEBYTECODE=1
alias tshark='/opt/wireshark/bin/tshark'
EOF
  SCRIPT

  config.vm.provision "env", type: "shell", privileged: false, inline: $envvars

  #Ubuntu package installation
  $shcmds = <<-SCRIPT
  apt-get update
  apt-get install -y python-pip
  SCRIPT
  
  config.vm.provision "apt", type: "shell", inline: $shcmds

  #Python dev env
  $pycmds = <<-SCRIPT
  pip install --upgrade --user pip
  pip install --user tox
  SCRIPT

  config.vm.provision "python", type: "shell", privileged: false, inline: $pycmds

  #Tshark compilation -- using shared folder
  config.vm.provision "tshark", type: "shell" do |s|
    s.inline = "/bin/bash /scripts/Shell/wireshark/compile_tshark.sh $1"
    s.privileged = true
    s.args = ["-c /scripts/Shell/wireshark/wireshark-master-ba-2.4-tar.gz -t -o /opt"]
  end

end
