# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7.5"
  config.vm.hostname = "sandbox"
  config.vm.define "centOS"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.name= "centOS_sandbox"
     vb.cpus = 2
     vb.memory = "1024"
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
   end

  config.vm.provision "proxy", type: "shell", run: "never" do |p|
      p.inline = 'grep -q "^proxy" $3 && sed "s@^proxy.\*@proxy=http://$1:$2@" -i.bak $3 || sed "\$a proxy=http://$1:$2" -i.bak $3'
      p.args = ["1.1.1.1", "8080", "/etc/yum.conf"]
  end

  $base_repos = <<-SCRIPT
      yum clean all
      yum-config-manager --disable *
      yum-config-manager --enable base extras updates
      yum repolist enabled
      yum update -y
  SCRIPT
  config.vm.provision "base_repos", type: "shell", run: "always" do |yum|
      yum.inline = $base_repos
  end
end
